### ISSUE TITLE
tramoseats - Problem with fixed coefficients

### ISSUE THREAD

**Issue by carlos-saez** [palatej/rjd3tramoseats#2]
There seems to be a bug when fixed coefficients are used for the ARIMA model in TRAMO. The following code reproduces the issue:
```
data <- Exports$Spain
custom_spec <- spec_tramoseats_default()
ts <- tramoseats(data, spec = custom_spec)    # this works

custom_spec$tramo$automodel$enabled <- FALSE
custom_spec$tramo$arima$theta[,1]$type <- "FIXED"
ts2 <- tramoseats(data, spec=custom_spec)    # this doesn't work
```
When executing the last line the following error message appears:
Error in .jcall("demetra/tramoseats/r/TramoSeats", "Ldemetra/tramoseats/io/protobuf/TramoSeatsOutput;",  : 
  java.lang.ArrayIndexOutOfBoundsException

An analogous error occurs when a series is loaded in the JDemetra+ desktop app, some ARIMA coefficient is fixed in the app, the obtained workspace is read with RJDemetra3 and jsa.read() is called on the corresponding sa.

**Comment by palatej** [comment]
Version 0.2.0
